export default [
  {
    name: 'Ana Silva',
    country: 'Brazil',
    skills: { android: true, css: true, html5: true, mac: false, windows: true },
    proficiency: 82,
    mobile: '+55 11 99999-0001',
    landline: '+55 11 3333-0001',
    address: 'São Paulo, SP',
  },
  {
    name: 'Bruno Santos',
    country: 'Portugal',
    skills: { android: false, css: true, html5: true, mac: true, windows: false },
    proficiency: 67,
    mobile: '+351 912 000 002',
    landline: '+351 213 000 002',
    address: 'Lisboa',
  },
  {
    name: 'Carla Oliveira',
    country: 'Spain',
    skills: { android: true, css: false, html5: true, mac: true, windows: true },
    proficiency: 91,
    mobile: '+34 612 000 003',
    landline: '+34 913 000 003',
    address: 'Madrid',
  },
  {
    name: 'Daniel Costa',
    country: 'Germany',
    skills: { android: false, css: true, html5: false, mac: false, windows: true },
    proficiency: 54,
    mobile: '+49 170 000 004',
    landline: '+49 30 000 004',
    address: 'Berlin',
  },
  {
    name: 'Elena Ferreira',
    country: 'France',
    skills: { android: true, css: true, html5: false, mac: true, windows: false },
    proficiency: 73,
    mobile: '+33 6 00 00 05',
    landline: '+33 1 00 00 05',
    address: 'Paris',
  },
  {
    name: 'Felipe Almeida',
    country: 'United Kingdom',
    skills: { android: false, css: true, html5: true, mac: false, windows: true },
    proficiency: 48,
    mobile: '+44 7700 000006',
    landline: '+44 20 0000 0006',
    address: 'London',
  },
];
