// FA4 icon names that map to a different FA6 icon name (without prefix/style).
export const FA4_RENAMES = {
  close: 'xmark',
  send: 'paper-plane',
  'send-o': 'paper-plane',
  gear: 'gear',
  cogs: 'gears',
  'files-o': 'copy',
  'question-circle-o': 'circle-question',
  'file-o': 'file',
  'folder-o': 'folder',
  'folder-open-o': 'folder-open',
  'trash-o': 'trash-can',
  remove: 'xmark',
  times: 'xmark',
  'times-circle': 'circle-xmark',
  'times-circle-o': 'circle-xmark',
  'check-circle-o': 'circle-check',
  'exclamation-circle': 'circle-exclamation',
  'exclamation-triangle': 'triangle-exclamation',
  'info-circle': 'circle-info',
  'play-circle-o': 'circle-play',
  'pause-circle-o': 'circle-pause',
  'stop-circle-o': 'circle-stop',
  'dot-circle-o': 'circle-dot',
  'minus-circle': 'circle-minus',
  'plus-circle': 'circle-plus',
  'arrow-circle-o-down': 'circle-arrow-down',
  'arrow-circle-o-up': 'circle-arrow-up',
  'arrow-circle-o-left': 'circle-arrow-left',
  'arrow-circle-o-right': 'circle-arrow-right',
  'caret-square-o-down': 'square-caret-down',
  'caret-square-o-up': 'square-caret-up',
  'caret-square-o-left': 'square-caret-left',
  'caret-square-o-right': 'square-caret-right',
  'picture-o': 'image',
  'photo': 'image',
  'file-image-o': 'file-image',
  'file-text-o': 'file-lines',
  'file-text': 'file-lines',
  'file-pdf-o': 'file-pdf',
  'file-word-o': 'file-word',
  'file-excel-o': 'file-excel',
  'file-powerpoint-o': 'file-powerpoint',
  'file-archive-o': 'file-zipper',
  'file-code-o': 'file-code',
  'file-audio-o': 'file-audio',
  'file-video-o': 'file-video',
  'file-movie-o': 'file-video',
  'file-photo-o': 'file-image',
  'file-picture-o': 'file-image',
  'file-sound-o': 'file-audio',
  'file-zip-o': 'file-zipper',
  'floppy-o': 'floppy-disk',
  'hdd-o': 'hard-drive',
  'bell-o': 'bell',
  'bookmark-o': 'bookmark',
  'building-o': 'building',
  'calendar-o': 'calendar',
  'calendar-check-o': 'calendar-check',
  'calendar-minus-o': 'calendar-minus',
  'calendar-plus-o': 'calendar-plus',
  'calendar-times-o': 'calendar-xmark',
  'clock-o': 'clock',
  'comment-o': 'comment',
  'comments-o': 'comments',
  'credit-card': 'credit-card',
  'credit-card-alt': 'credit-card',
  'dashboard': 'gauge',
  'edit': 'pen-to-square',
  'eject': 'eject',
  'eye-slash': 'eye-slash',
  'feed': 'rss',
  'flash': 'bolt',
  'frown-o': 'face-frown',
  'futbol-o': 'futbol',
  'glass': 'martini-glass-empty',
  'group': 'users',
  'hand-o-down': 'hand-point-down',
  'hand-o-left': 'hand-point-left',
  'hand-o-right': 'hand-point-right',
  'hand-o-up': 'hand-point-up',
  'hand-stop-o': 'hand',
  'hand-paper-o': 'hand',
  'hospital-o': 'hospital',
  'hourglass-o': 'hourglass',
  'legal': 'gavel',
  'lemon-o': 'lemon',
  'life-bouy': 'life-ring',
  'life-buoy': 'life-ring',
  'life-saver': 'life-ring',
  'lightbulb-o': 'lightbulb',
  'linkedin-square': 'linkedin',
  'linkedin': 'linkedin',
  'list-alt': 'rectangle-list',
  'mail-forward': 'share',
  'mail-reply': 'reply',
  'mail-reply-all': 'reply-all',
  'map-o': 'map',
  'meh-o': 'face-meh',
  'mobile-phone': 'mobile-screen-button',
  'mobile': 'mobile-screen-button',
  'money': 'money-bill',
  'moon-o': 'moon',
  'mortar-board': 'graduation-cap',
  'navicon': 'bars',
  'newspaper-o': 'newspaper',
  'paste': 'paste',
  'pencil-square-o': 'pen-to-square',
  'pencil-square': 'pen-to-square',
  'pencil': 'pencil',
  'play-circle': 'circle-play',
  'plus-square-o': 'square-plus',
  'minus-square-o': 'square-minus',
  'check-square-o': 'square-check',
  'square-o': 'square',
  'star-half-o': 'star-half-stroke',
  'star-half-empty': 'star-half-stroke',
  'star-half-full': 'star-half-stroke',
  'sticky-note-o': 'note-sticky',
  'sun-o': 'sun',
  'support': 'life-ring',
  'tachometer': 'gauge',
  'television': 'tv',
  'thumb-tack': 'thumbtack',
  'thumbs-o-down': 'thumbs-down',
  'thumbs-o-up': 'thumbs-up',
  'ticket': 'ticket',
  'toggle-down': 'caret-down',
  'toggle-up': 'caret-up',
  'toggle-left': 'caret-left',
  'toggle-right': 'caret-right',
  refresh: 'arrow-rotate-right',
  'unsorted': 'sort',
  'warning': 'triangle-exclamation',
  'wheelchair-alt': 'wheelchair-move',
  'bar-chart': 'chart-column',
  'bar-chart-o': 'chart-column',
  'area-chart': 'chart-area',
  'line-chart': 'chart-line',
  'pie-chart': 'chart-pie',
  'external-link': 'arrow-up-right-from-square',
  'external-link-square': 'square-arrow-up-right',
  'video-camera': 'video',
  'chain': 'link',
  'chain-broken': 'link-slash',
  'unlink': 'link-slash',
  'reorder': 'bars',
  'dedent': 'outdent',
  'rotate-left': 'rotate-left',
  'rotate-right': 'rotate-right',
  'institution': 'building-columns',
  'bank': 'building-columns',
  'automobile': 'car',
  'cab': 'taxi',
  'cutlery': 'utensils',
  'desktop': 'desktop',
  'ge': 'empire',
  'ra': 'rebel',
  'resistance': 'rebel',
  'intersex': 'mars-and-venus',
  'transgender': 'mars-and-venus',
  'transgender-alt': 'transgender',
  'meanpath': 'font-awesome',
  'font-awesome': 'font-awesome',
  'google-plus': 'google-plus-g',
  'google-plus-circle': 'google-plus-g',
  'google-plus-official': 'google-plus-g',
  'google-plus-square': 'square-google-plus',
  'facebook-f': 'facebook-f',
  'facebook-official': 'facebook',
  'bitbucket-square': 'bitbucket',
  'github-square': 'github',
  'git-square': 'git',
  'behance-square': 'behance',
  'deviantart': 'deviantart',
  'dribbble': 'dribbble',
  'dropbox': 'dropbox',
  'foursquare': 'foursquare',
  'instagram': 'instagram',
  'lastfm-square': 'lastfm',
  'pinterest-square': 'pinterest',
  'reddit-square': 'reddit',
  'skype': 'skype',
  'slack': 'slack',
  'snapchat-ghost': 'snapchat',
  'snapchat-square': 'snapchat',
  'spotify': 'spotify',
  'stack-overflow': 'stack-overflow',
  'steam-square': 'steam',
  'tumblr-square': 'tumblr',
  'twitter-square': 'twitter',
  'vimeo-square': 'vimeo',
  'xing-square': 'xing',
  'youtube-square': 'youtube',
  'weixin': 'weixin',
  'wechat': 'weixin',
};

// Icons that should use the brands (fab) pack.
export const FA4_BRANDS = new Set([
  '500px', 'adn', 'amazon', 'android', 'angellist', 'apple', 'behance',
  'behance-square', 'bitbucket', 'bitbucket-square', 'bitcoin', 'black-tie',
  'bluetooth', 'bluetooth-b', 'btc', 'buysellads', 'cc-amex', 'cc-diners-club',
  'cc-discover', 'cc-jcb', 'cc-mastercard', 'cc-paypal', 'cc-stripe', 'cc-visa',
  'chrome', 'codepen', 'codiepie', 'connectdevelop', 'contao', 'css3',
  'dashcube', 'delicious', 'deviantart', 'digg', 'dribbble', 'dropbox', 'drupal',
  'edge', 'empire', 'envira', 'expeditedssl', 'facebook', 'facebook-f',
  'facebook-official', 'facebook-square', 'firefox', 'first-order', 'flickr',
  'fonticons', 'fort-awesome', 'forumbee', 'foursquare', 'ge', 'get-pocket',
  'gg', 'gg-circle', 'git', 'git-square', 'github', 'github-alt', 'github-square',
  'gitlab', 'gittip', 'glide', 'glide-g', 'google', 'google-plus',
  'google-plus-circle', 'google-plus-official', 'google-plus-square',
  'google-wallet', 'gratipay', 'houzz', 'html5', 'instagram', 'internet-explorer',
  'ioxhost', 'joomla', 'jsfiddle', 'lastfm', 'lastfm-square', 'leanpub',
  'linkedin', 'linkedin-square', 'linux', 'maxcdn', 'meanpath', 'medium',
  'mixcloud', 'modx', 'odnoklassniki', 'odnoklassniki-square', 'opencart',
  'openid', 'opera', 'optin-monster', 'pagelines', 'paypal', 'pied-piper',
  'pied-piper-alt', 'pied-piper-pp', 'pinterest', 'pinterest-p', 'pinterest-square',
  'product-hunt', 'qq', 'ra', 'rebel', 'reddit', 'reddit-alien', 'reddit-square',
  'renren', 'resistance', 'safari', 'scribd', 'sellsy', 'share-alt', 'share-alt-square',
  'shirtsinbulk', 'simplybuilt', 'skyatlas', 'skype', 'slack', 'slideshare',
  'snapchat', 'snapchat-ghost', 'snapchat-square', 'soundcloud', 'spotify',
  'stack-exchange', 'stack-overflow', 'steam', 'steam-square', 'stumbleupon',
  'stumbleupon-circle', 'tencent-weibo', 'themeisle', 'trello', 'tripadvisor',
  'tumblr', 'tumblr-square', 'twitch', 'twitter', 'twitter-square', 'usb',
  'viacoin', 'viadeo', 'viadeo-square', 'vimeo', 'vimeo-square', 'vine', 'vk',
  'wechat', 'weibo', 'weixin', 'whatsapp', 'wikipedia-w', 'windows', 'wordpress',
  'wpbeginner', 'wpforms', 'xing', 'xing-square', 'yahoo', 'y-combinator',
  'y-combinator-square', 'yelp', 'yoast', 'youtube', 'youtube-play', 'youtube-square',
  'yc', 'yc-square',
]);

// FA4 -o icons that should stay solid (not regular) in FA6.
export const FA4_SOLID_O = new Set([
  'circle-o-notch',
]);
